import type { Metadata } from "next";
import { Noto_Sans, Caveat } from "next/font/google";
import "./globals.css";
import Providers from "@/components/Providers";

const notoSans = Noto_Sans({
  weight: ["100", "300", "600", "700", "900"],
  subsets: ["latin"],
  variable: "--font-noto-sans",
});

const font_caveat = Caveat({ subsets: ["latin"], variable: "--font-caveat" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${notoSans.variable} ${font_caveat.variable} font-sans`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
